### ISSUE TITLE
NativeAOT sample doesn't load Blazor app - stuck on "Loading..."

### ISSUE THREAD

**Issue by MatthewKing** [tryphotino/photino.Blazor#109] opened 2024-01-31 13:37 UTC
I'm having trouble getting native AOT working with Photino.Blazor.
I thought I was doing something wrong with my app, but then I noticed that the NativeAOT sample has the exact same issue.
When I run the sample (either via Visual Studio, or running the exe after `dotnet publish`), the Blazor application never loads. Rather, I just get stuck with the "Loading..." div in index.html.

Steps to reproduce:
1. Clone the repository.
2. Run the Photino.Blazor.NativeAOT sample.
3. Observe that the Blazor app never loads, and we're just stuck with the "Loading..." div.

FWIW, everything runs as expected if the PublishAot property is removed from the project file.

Happy to provide any more information required if you can't reproduce this.

**Comment by ottodobretsberger** [comment] 2024-02-01 17:32
We need to investigate the source of  this behavior. Thank you for pointing it out. It's on our backlog.

**Comment by ivanjx** [comment] 2024-02-20 14:56
duplicate of #106 ?

**Comment by MatthewKing** [comment] 2024-03-10 14:21
I think it relates to the JSON serialization in [IpcCommon](https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebView/WebView/src/IpcCommon.cs) as called by [IpcReceiver](https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebView/WebView/src/IpcReceiver.cs). I'm not currently familiar enough with AOT or WebView to know if this can be worked around or not.

**Comment by ivanjx** [comment] 2024-03-17 04:36
for starter, [`TryDeserialize`](https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebView/WebView/src/IpcCommon.cs#L37) needs a `JsonTypeInfo<T>` parameter that can be taken from `[JsonSerializable]` annotated class. we also need to know what types are being passed into `Serialize` and have to annotate those types too.

**Comment by ivanjx** [comment] 2024-03-17 04:41
i guess we just have to wait https://github.com/dotnet/aspnetcore/issues/51598

**Comment by scottkuhl** [comment] 2024-07-13 17:21
This issue seems to be more than just NativeAOT.  None of the sample Blazor apps work.  They are all stuck on "Loading..."

**Comment by philippjbauer** [comment] 2024-10-17 14:50
This issue has been resolved in Photino.Blazor 3.1.10
https://github.com/tryphotino/photino.Blazor/releases/tag/v3.1.10

**Closed by philippjbauer** 2024-10-17 14:50 UTC
Labels: bug, All OS

**Comment by ivanjx** [comment] 2024-10-26 12:19
i tried running the sample app but keeps failing on publish:
```
Photino.Blazor.NativeAOT failed with 1 error(s) (4,6s) → bin\Release\net8.0\win-x64\Photino.Blazor.NativeAOT.dll
    C:\Users\x\.nuget\packages\microsoft.dotnet.ilcompiler\8.0.8\build\Microsoft.NETCore.Native.targets(308,5): error MSB3073: The command ""C:\Users\x\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\8.0.8\tools\\ilc" @"obj\Release\net8.0\win-x64\native\Photino.Blazor.NativeAOT.ilc.rsp"" exited with code -1073740791.

Build failed with 1 error(s) and 4 warning(s) in 5,8s
```

the csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk.Razor">
	
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ApplicationIcon>favicon.ico</ApplicationIcon>
		<PublishAot>true</PublishAot>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Photino.Blazor\Photino.Blazor.csproj" />
	</ItemGroup>

	<ItemGroup Condition="$(RuntimeIdentifier.StartsWith('win'))">
		<RdXmlFile Include="rd.xml" />
		<RdXmlFile Include="Microsoft.AspNetCore.Components.Web.rd.xml" />
		<IlcArg Include="--nometadatablocking" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="wwwroot\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <None Update="favicon.ico">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
```

the error seems to be caused by `<IlcArg Include="--nometadatablocking" />` but if i remove it the app will stuck on loading.

**Comment by schaveyt** [comment] 2024-12-17 07:19
I am getting the same incorrect behavior. In fact, I cannot create a publish executable at all.

**Comment by schaveyt** [comment] 2025-03-11 02:49
Pull down the latest of this repo and attempt to build the AOT sample. It just does not BUILD 🙃
