### ISSUE TITLE
Links `<a href=""></a>` don't work on macOS

### ISSUE THREAD

**Issue by Jinjinov** [tryphotino/photino.Blazor#70] opened 2022-11-22 08:07 UTC
Links work normally on Windows and Linux but `<a href="http://blazor.net">About</a>` does nothing on macOS

Steps to reproduce:

1. open https://github.com/tryphotino/photino.Blazor/tree/master/Samples/Photino.Blazor.Sample on macOS
2. build and run
3. click on the `About` link

**Comment by philippjbauer** [comment] 2023-01-29 18:53
Closed as duplicate of https://github.com/tryphotino/photino.NET/issues/110

**Closed** 2023-01-29 18:53 UTC
