### ISSUE TITLE
`Microsoft.JSInterop.JSException: element.AddEventListener is not a function` errors thrown to StdOut

### ISSUE THREAD

**Issue by Smurf-IV** [tryphotino/photino.Blazor#17] opened 2021-03-15 15:18 UTC
![image](https://user-images.githubusercontent.com/2418812/111176974-b7835b00-85a1-11eb-9b37-b28bfc6be131.png)

**Comment by MikeYeager** [comment] 2021-03-18 15:49
Thanks for the post. Please join the discussion on #18

**Comment by ottodobretsberger** [comment] 2021-03-25 17:05
For repro purposed we would need some more information about the running OS, the steps taken to trigger the error, etc.
More detail would help us with that investigation.

**Comment by Smurf-IV** [comment] 2021-03-26 12:02
Use `Blazorise`.
Add A `TextInput`
Start the `Blazor` application in `Photino`.

**Comment by ottodobretsberger** [comment] 2021-04-01 15:14
We are planning to update the Blazor source code from Microsoft, since the current internal version is still based on 3.1
That may fix it. If that doesn't, we can consider looking further into the issue with Blazorise.

**Comment by Tewr** [comment] 2021-12-15 10:37
Hello. This came up as [an issue earlier this year](https://github.com/Tewr/BlazorFileReader/issues/174) in a blazor component I'm maintaining, and I'm pretty sure the underlying error is the (non-)management of `ElementReference`, as described in #28

**Comment by MikeYeager** [comment] 2021-12-16 15:51
If the community fixes and does a pull request, we're happy to merge it and post a new version.

**Comment by MikeYeager** [comment] 2022-01-13 17:27
@Tewr Photino.Blazor is now updated to use .NET 6. Please try again and let us know if this is now fixed.

**Comment by Denny09310** [comment] 2022-03-12 18:51
> @Tewr Photino.Blazor is now updated to use .NET 6. Please try again and let us know if this is now fixed.

Hi, I'm new to Photino with Blazor and maybe someone has found a workaround, but the problem is still present.
Using the template provided in the repo as starting point I was trying to use Blazored.LocalStorage functionalities but when I try to Save/Access into the local storage it thorws an error.
I don't know if it's the same problem as this, but I'll try to include as much details as possible.
I'll include event the Blazored service configuration, maybe I'm doing something wrong there.

![image](https://user-images.githubusercontent.com/50493437/158030913-2f16d22a-e647-4a97-90bc-3719db0c6eea.png)
![image](https://user-images.githubusercontent.com/50493437/158030953-5e586d74-ff64-443d-8d22-8392a8cfbab6.png)

**Comment by ottodobretsberger** [comment] 2022-03-17 14:49
Thank you for pointing this out. As time permits we will look into this more (unless there's community involvement/help before we get to do so)

**Comment by MikeYeager** [comment] 2024-10-17 16:46
We believe this is closed along with issue https://github.com/tryphotino/photino.Blazor/issues/28

**Closed by MikeYeager** 2024-10-17 16:46 UTC
Labels: bug, help wanted, question, All OS
