### ISSUE TITLE
How to correctly open native file/folder dialogs ?

### ISSUE THREAD

**Issue by Crauzer** [tryphotino/photino.Blazor#76] opened 2023-02-20 10:20 UTC
I tried using the `NativeFileDialog` package as recommended in another issue but that led to some strange random crashes so I decided to [create my own dialog library ](https://github.com/tryphotino/photino.NET/issues/22#issuecomment-1436644959) but the issue persists.

When I open a dialog in a button's `OnClick` callback, both async and sync approaches are broken. If you spam clicks between the dialog and the window, the application freezes and crashes after a few seconds. What could be the reason for this behavior ?

I found [this issue](https://github.com/btzy/nativefiledialog-extended/pull/47), but I have no idea what I can do to solve this.

**Comment by Crauzer** [comment] 2023-02-20 11:16
I tried using https://www.nuget.org/packages/WindowsAPICodePackShell but the same exact behavior happens,

**Comment by Crauzer** [comment] 2023-02-20 11:28
This is the error which gets thrown:
```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/tryphotino/photino.Blazor/issues/76#) <System>
  <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" /> 
  <EventID>1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2023-02-20T11:18:49.1659545Z" /> 
  <EventRecordID>16917</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="17564" ThreadID="24624" /> 
  <Channel>Application</Channel> 
  <Computer>crauzer</Computer> 
  <Security UserID="S-1-5-21-3386161964-2172295773-587479165-1001" /> 
  </System>
[-](https://github.com/tryphotino/photino.Blazor/issues/76#) <EventData>
  <Data Name="AppName">lol2gltf.exe</Data> 
  <Data Name="AppVersion">3.0.0.0</Data> 
  <Data Name="AppTimeStamp">63cf74d2</Data> 
  <Data Name="ModuleName">EmbeddedBrowserWebView.dll</Data> 
  <Data Name="ModuleVersion">110.0.1587.49</Data> 
  <Data Name="ModuleTimeStamp">63ed667c</Data> 
  <Data Name="ExceptionCode">80000003</Data> 
  <Data Name="FaultingOffset">000000000037185d</Data> 
  <Data Name="ProcessId">0x5c4c</Data> 
  <Data Name="ProcessCreationTime">0x1d9451d088f93e1</Data> 
  <Data Name="AppPath">X:\dev\lol2gltf\lol2gltf\bin\x64\Debug\net6.0-windows\win-x64\lol2gltf.exe</Data> 
  <Data Name="ModulePath">C:\Program Files (x86)\Microsoft\EdgeWebView\Application\110.0.1587.49\EBWebView\x64\EmbeddedBrowserWebView.dll</Data> 
  <Data Name="IntegratorReportId">a54f00e8-0e9f-48e4-b81f-54664e6dd4eb</Data> 
  <Data Name="PackageFullName" /> 
  <Data Name="PackageRelativeAppId" /> 
  </EventData>
  </Event>
  ```

**Comment by Crauzer** [comment] 2023-02-20 11:51
https://github.com/MicrosoftEdge/WebView2Feedback/issues/2310

**Comment by MikeYeager** [comment] 2023-02-23 16:38
@Crauzer We have run into this issue as well and don't have a solution for it. We do use PostMessage instead of SendMessage as mentioned in one of the comments of the related issue you mentioned.

**Comment by Crauzer** [comment] 2023-02-23 22:10
> @Crauzer We have run into this issue as well and don't have a solution for it. We do use PostMessage instead of SendMessage as mentioned in one of the comments of the related issue you mentioned.

Btw I tried opening dialogs in Blazor WebView hosted in a WPF app and it also produces this same crash, I guess it is an issue that the WebView people have to fix.

**Comment by Kizari** [comment] 2024-04-10 07:10
I ran into this problem with a Blazor Desktop app I created a couple of years back using BlazorWebView in WPF.

I apologise if this isn't the same issue you've described here, but I figured it couldn't hurt to share just in case.

The solution for me was to invoke the Windows API **asynchronously** (the synchronous `Invoke` did **not** work) on the main thread.

I know it sounds a bit silly, but it I found it on one of the MS repositories recommended by an MS employee, and it did work for me.

Because it's Windows API stuff, this was in a method on a windows implementation of my `IPlatformService` interface, which I injected into the Blazor application. Unfortunately I didn't do anything with any other operating systems with this application, so if the issue exists on those then I don't have anything that may help there.

`_window` is a reference to my WPF `MainWindow`, but I would assume there are other ways to access a dispatcher in Photino? I've only just started using it today, so not too sure how things work just yet.

```csharp
var dialog = new OpenFileDialog
{
    Filter = "Text File|*.txt"
};

var result = await _window.Dispatcher.InvokeAsync(() => dialog.ShowDialog());

if (result == true)
{
    var filePath = dialog.FileName;
    // Do whatever you like with the file
}
```

Hopefully this will help in some way. Best of luck!

**Comment by philippjbauer** [comment] 2024-04-11 15:53
FYI: I can confirm that this behavior only affects Windows. macOS and Linux don't depend on the same WebView implementation, so this was expected.

**Comment by philippjbauer** [comment] 2024-04-11 15:57
Probably related to issue https://github.com/tryphotino/photino.Samples/issues/11

**Comment by philippjbauer** [comment] 2024-04-11 17:09
@Kizari @Crauzer 

I tried to reproduce the issue on Windows as well and it works for me with the caveat that a Console.WriteLine call is not routed to the terminal I run the app from but is shown in the Debug Console when you run the app in that mode. See this screengrab

https://github.com/tryphotino/photino.Blazor/assets/3707196/250d627a-29cc-4f04-9c7f-840ee49c670d

Can you confirm this? What is the difference between our code and yours that break it, do you have a repo we can check out to replicate the behavior?

**Comment by Kizari** [comment] 2024-04-15 11:45
@philippjbauer 

My previous example was showing how I resolved the issue in a WPF/Blazor hybrid application in the past, but I can confirm the bug exists in Photino after trying it out.

The difference between our approach and yours is that you're using Blazor's InputFile web control, while we're using Photino's native API. This may be an option for @Crauzer, but in my case I can't open a select **folder** dialog through web code, hence my preference for this approach.

**ConfigurationComponent.razor**
```csharp
@page "/configuration"

@using Photino.Blazor

@inject PhotinoBlazorApp Photino

<input type="text" @bind="Configuration.DataRoot" readonly />
<button @onclick="Browse">Browse</button>

@code
{
    private void Browse()
    {
        var folders = Photino.MainWindow.ShowOpenFolder();
        if (folders != null)
        {
            Configuration.DataRoot = folders[0];
        }
    }
}
```

The bug presents exactly the same way as it did for me in WPF before I fixed it. It only happens if you open the folder (or file) dialog, and leave it open for a while (it's variable, I have had it happen as quickly as about 5-10 seconds, or as slow as 30+ seconds). There's no need to do anything once the dialog is open, it'll simply crash after a period of time. It's not uncommon for the dialog to remain open this long when digging for a file or folder that is nested several folders deep.

Looking at the code for `ShowOpenDialog` in `PhotinoWindow.cs`, I note that the call back to Photino Native is wrapped in an `Invoke` call to run it on the main thread, but this is synchronous. Presuming the same Windows APIs are invoked under the hood as WPF invokes, this would cause the crash when called from Blazor.

I'll clone Photino.NET and see if I can get this working.

**Comment by Crauzer** [comment] 2024-04-15 11:55
Unfortunately I've stopped using Photino and Blazor altogether as I was very dissatisfied with the overall development experience (Mainly from Blazor's side). This was one of the main issues which prompted me to switch to the Tauri ecosystem (Rust/React) for my other apps.

I remember I tried every single way that I could think of calling the dialog but I eventually settled on using the microsoft dialog shell library. You can see [here](https://github.com/Crauzer/lol2gltf/blob/c4d905772a866cbacea720abf8d56b158b396696/lol2gltf/Pages/MapGeometry.razor#L171) and [here](https://github.com/Crauzer/lol2gltf/blob/c4d905772a866cbacea720abf8d56b158b396696/lol2gltf/Pages/MapGeometry.razor#L171) how I settled on using it. I wasn't able to use the Photino dialog API as it didn't exist before but it does seem like it still doesn't fix this issue.

**Comment by Kizari** [comment] 2024-04-15 12:06
I've found the fix. Unfortunately someone closer to the project would need to decide how to handle implementing it due to how it may only affect Blazor.

Here's the original implementation:
**Photino.NET / PhotinoWindow.NET.cs**
```csharp
    private string[] ShowOpenDialog(bool foldersOnly, string title, string defaultPath, bool multiSelect, (string Name, string[] Extensions)[] filters)
    {
        defaultPath ??= Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
        filters ??= Array.Empty<(string, string[])>();

        var results = Array.Empty<string>();
        var nativeFilters = GetNativeFilters(filters, foldersOnly);

        Invoke(() =>
        {
            var ptrResults = foldersOnly ?
                Photino_ShowOpenFolder(_nativeInstance, title, defaultPath, multiSelect, out var resultCount) :
                Photino_ShowOpenFile(_nativeInstance, title, defaultPath, multiSelect, nativeFilters, nativeFilters.Length, out resultCount);
            if (resultCount == 0) return;

            var ptrArray = new IntPtr[resultCount];
            results = new string[resultCount];
            Marshal.Copy(ptrResults, ptrArray, 0, resultCount);
            for (var i = 0; i < resultCount; i++)
            {
                results[i] = Marshal.PtrToStringAuto(ptrArray[i]);
            }
        });

        return results;
    }
```

And here is my implementation that fixes the issue:
```
private async Task<string[]> ShowOpenDialogAsync(bool foldersOnly, string title, string defaultPath, bool multiSelect, (string Name, string[] Extensions)[] filters)
    {
        defaultPath ??= Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
        filters ??= Array.Empty<(string, string[])>();

        var results = Array.Empty<string>();
        var nativeFilters = GetNativeFilters(filters, foldersOnly);

        await Task.Run(() =>
            Invoke(() =>
            {
                var ptrResults = foldersOnly
                    ? Photino_ShowOpenFolder(_nativeInstance, title, defaultPath, multiSelect, out var resultCount)
                    : Photino_ShowOpenFile(_nativeInstance, title, defaultPath, multiSelect, nativeFilters,
                        nativeFilters.Length, out resultCount);
                if (resultCount == 0) return;

                var ptrArray = new IntPtr[resultCount];
                results = new string[resultCount];
                Marshal.Copy(ptrResults, ptrArray, 0, resultCount);
                for (var i = 0; i < resultCount; i++)
                {
                    results[i] = Marshal.PtrToStringAuto(ptrArray[i]);
                }
            }));

        return results;
    }
```

All I did was wrap the invoke call in a `Task.Run`, since Photino native doesn't have an `InvokeAsync` method to call. Using this version of Photino and calling this asynchronous version of `ShowOpenDialogAsync` instead, my application no longer crashes when selecting a folder.

While I'd happily submit a PR, I'm unsure how it would be best to handle this. From my perspective the ideal option would be to remove the synchronous methods and replace the asynchronous versions to prevent users calling the broken ones, but assuming the synchronous methods work fine outside of Blazor, this is obviously not ideal for any of the other platforms.

**Comment by MikeYeager** [comment] 2024-10-17 16:40
Async calls have been implemented for all 3 dialogs in Photino.NET and will be released with the next version. (v3.2.x)

**Closed by MikeYeager** 2024-10-17 16:40 UTC
Labels: Windows, Known Issue
