### ISSUE TITLE
File "app://app/" could not be found.

### ISSUE THREAD

**Issue by hbxtlhx** [tryphotino/photino.Blazor#12] opened 2021-03-11 06:33 UTC
on debian or macos:
Photino.Blazor(1.1.1)
File "app://app/" could not be found.

**Comment by ChristianWeyer** [comment] 2021-03-11 06:42
Yep. Having the same here on macOS with latest 1.1.1.

**Comment by porteregr** [comment] 2021-03-11 16:12
Seeing this on Debian as well. Running on a Raspberry PI with a custom built arm version of Photino.Native.

**Comment by ChristianWeyer** [comment] 2021-03-14 11:39
Is there already any kind of idea when you will be able to look at it @philippjbauer ? If you need more testing or further input, just let me know :-)

**Comment by sharpninja** [comment] 2021-03-22 00:57
I know what the issue is, I get it on Kubuntu 20.10 with both .Net 5.0.2 and the current .Net 6.0 Preview.  The Task at 
```csharp
      Task.Factory.StartNew<Task>((Func<Task>) (async () =>
      {
        try
        {
          await ComponentsDesktop.RunAsync<TStartup>(new IPC(ComponentsDesktop.photinoWindow), appLifetimeCts.Token);
        }
        catch (Exception ex)
        {
          ComponentsDesktop.UnhandledException(ex);
          throw;
        }
      }));
```
is queued up but never executed by the dispatcher, so it then falls into 
```csharp
      try
      {
        ComponentsDesktop.photinoWindow.Load(ComponentsDesktop.BlazorAppScheme + "://app/");
        ComponentsDesktop.photinoWindow.WaitForClose();
      }
      finally
      {
        appLifetimeCts.Cancel();
      }
```
which generates the error.

If `private static async Task RunAsync<TStartup>(IPC ipc, CancellationToken appLifetime)` was made public then the Blazor app could be fired up independently.

**Comment by philippjbauer** [comment] 2021-04-01 22:11
The issue was fixed in photino.NET PR #30: https://github.com/tryphotino/photino.NET/pull/30

Another issue came up afterwards in the Native project: https://github.com/tryphotino/photino.Native/issues/60

**Closed by philippjbauer** 2021-04-01 22:11 UTC
Labels: Linux, bug, macOS

**Comment by JinShil** [comment] 2021-07-11 10:46
This issue still exists.  For some reason the changes in https://github.com/tryphotino/photino.NET/pull/30 do not appear in the latest source code.
